"""add questions.image_hash for dedup

Revision ID: 161851d2f63f
Revises: 8ac7bf6a7a43
Create Date: 2026-09-14 23:32:06.571972
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '161851d2f63f'
down_revision = '8ac7bf6a7a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_questions_image_hash'), ['image_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_image_hash'))
        batch_op.drop_column('image_hash')

    # ### end Alembic commands ###
