"""add classes and class_members

Revision ID: 55c91901b5d9
Revises: 74fbffade73a
Create Date: 2026-09-27 16:51:50.745189
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '55c91901b5d9'
down_revision = '74fbffade73a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('class_members',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('class_id', 'student_id')
    )
    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.create_index('ix_classmember_student_class', ['student_id', 'class_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_members', schema=None) as batch_op:
        batch_op.drop_index('ix_classmember_student_class')

    op.drop_table('class_members')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_teacher_id'))

    op.drop_table('classes')
    # ### end Alembic commands ###
