"""add question verification fields

Revision ID: 7d967aaa71b5
Revises: b98b7ec07b27
Create Date: 2026-09-27 14:57:14.742490
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '7d967aaa71b5'
down_revision = 'b98b7ec07b27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('verification_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_methods', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_methods')
        batch_op.drop_column('verification_confidence')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
