"""add questions.starred

Revision ID: 7f0da979939c
Revises: 55c91901b5d9
Create Date: 2026-09-29 13:37:53.095351
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '7f0da979939c'
down_revision = '55c91901b5d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starred', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_questions_starred'), ['starred'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_starred'))
        batch_op.drop_column('starred')

    # ### end Alembic commands ###
