"""add knowledge points + question link

Revision ID: b09bda59c235
Revises: 7d967aaa71b5
Create Date: 2026-09-27 15:46:40.037679
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'b09bda59c235'
down_revision = '7d967aaa71b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_points_name'), ['name'], unique=True)

    op.create_table('question_knowledge_points',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'knowledge_point_id')
    )
    with op.batch_alter_table('question_knowledge_points', schema=None) as batch_op:
        batch_op.create_index('ix_qkp_kp_question', ['knowledge_point_id', 'question_id'], unique=False)
        batch_op.create_index('ix_qkp_question_kp', ['question_id', 'knowledge_point_id'], unique=True)

    # 注意：不要在此迁移中补 questions 的 verification 列——
    # 7d967aaa71b5 已负责；autogenerate 曾因开发库缺列误 diff 出重复 DDL。


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_knowledge_points', schema=None) as batch_op:
        batch_op.drop_index('ix_qkp_question_kp')
        batch_op.drop_index('ix_qkp_kp_question')

    op.drop_table('question_knowledge_points')
    with op.batch_alter_table('knowledge_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_points_name'))

    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
