"""add user token_version

Revision ID: c463cd3fa41c
Revises: 7f0da979939c
Create Date: 2026-09-30 00:12:43.165714
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'c463cd3fa41c'
down_revision = '7f0da979939c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default 保证存量行为 NOT NULL 列回填 0（SQLite/MySQL 加列要求）
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('token_version', sa.Integer(), nullable=False, server_default=sa.text('0'))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###
