"""add questions.ocr_text

Revision ID: fd4aa70dcf97
Revises: 5167fa289d4f
Create Date: 2026-09-13 17:01:15.231453
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'fd4aa70dcf97'
down_revision = '5167fa289d4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')

    # ### end Alembic commands ###
